# OS ---------------------------------------------------------------------------
os: linux

# meta -------------------------------------------------------------------------
language: r
cache: packages
latex: false

# Stages -----------------------------------------------------------------------

install: true
script:
  - Rscript -e 'if (!requireNamespace("lintr")) install.packages("lintr")'
  - R CMD build .
  - R CMD INSTALL *.tar.gz
  - Rscript -e 'lintr::lint_package()'
